### ISSUE TITLE
Feature Request: Add button to hide documentation

### ISSUE THREAD

**Issue by ghost** [denkwerk/npm-dw-styleguide#5]
Similar to the button "View Source" that reveals a module's source code, a button revealing / hiding the markdown documentation would come in handy to not lose overview (at least when heavily using the documentation feature). 

Perhaps this can come along with an option deciding if the documentation should be visible or hidden on initial page load.

**Comment by mariusbuescher** [comment]
Fixed with 9bac1e09f8ae0059887c7bd4e38edb0e4c85180c
